/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dineshreddy
 */
public class Maven extends Backend {

    /**
     * Creates new form Maven
     */
    public Maven() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")

    public static String INPUTVALUE;

    public void runOnce() {
        // Get PC
        // opcode(PC)
        // Increment PC
        System.out.println("~~~Running runOnce~~~");
        String getPC = "";
        for (int i = 0; i < PC.length; i++){
            getPC += PC[i];
        }
        int intPC = Integer.parseInt(getPC,2);
        System.out.println("PC: " + intPC);
        String input = "";
        for (int i = 0; i < 16; i++){
            input += RAM[intPC][i];
        }
        PCincrement();
        opcode(input);
        refresh();
        update();
        // System.out.println("~~~ OPCODE: " + opcode);
        getPC = "";
        for (int i = 0; i < PC.length; i++){
            getPC += PC[i];
        }
        // Make sure to still increment at the end
    }

    public void runAll() {
        // IF BREAKS, opcode return back to string
        System.out.println("~~~Running runAll~~~");
        String getPC = "";
        for (int i = 0; i < PC.length; i++){
            getPC += PC[i];
        }
        int intPC = Integer.parseInt(getPC,2);
        String input = "";
        for (int i = 0; i < 16; i++){
            input += RAM[intPC][i];
        }
        PCincrement();
        int opcode = opcode(input);
        refresh();
        update();
        System.out.println("~~~ OPCODE: " + opcode);
        getPC = "";
        for (int i = 0; i < PC.length; i++){
            getPC += PC[i];
        }
        intPC = Integer.parseInt(getPC,2);
        input = "";
        for (int i = 0; i < 16; i++){
            input += RAM[intPC][i];
        }
        System.out.println("PC: " + intPC);
        while (opcode != 0){
            getPC = "";
            for (int i = 0; i < PC.length; i++){
                getPC += PC[i];
            }
            intPC = Integer.parseInt(getPC,2);
            input = "";
            for (int i = 0; i < 16; i++){
                input += RAM[intPC][i];
            }
            PCincrement();
            opcode = opcode(input);
            refresh();
            update();
            System.out.println("Input: " + input);
            getPC = "";
            for (int i = 0; i < PC.length; i++){
                getPC += PC[i];
            }
            intPC = Integer.parseInt(getPC,2);
            input = "";
            for (int i = 0; i < 16; i++){
                input += RAM[intPC][i];
            }
            System.out.println("PC: " + intPC);
        }
    }

    public void update(){
        gpr0Input.setText(showGPR0);
        gpr1Input.setText(showGPR1);
        gpr2Input.setText(showGPR2);
        gpr3Input.setText(showGPR3);
        ixr1Input.setText(showXR0);
        ixr2Input.setText(showXR1);
        ixr3Input.setText(showXR2);
        pcInput.setText(showPC);
        marInput.setText(showMAR);
        mbrInput.setText(showMBR);
        irInput.setText(showIR);
        mfrInput.setText(showMFR);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gpr0Input = new javax.swing.JTextField();
        gpr1Input = new javax.swing.JTextField();
        gpr2Input = new javax.swing.JTextField();
        gpr3Input = new javax.swing.JTextField();
        ixr1Input = new javax.swing.JTextField();
        ixr2Input = new javax.swing.JTextField();
        ixr3Input = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        gpr0Load = new javax.swing.JButton();
        gpr1Load = new javax.swing.JButton();
        gpr2Load = new javax.swing.JButton();
        gpr3Load = new javax.swing.JButton();
        ixr1Load = new javax.swing.JButton();
        ixr2Load = new javax.swing.JButton();
        ixr3Load = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        pcLoad = new javax.swing.JButton();
        marLoad = new javax.swing.JButton();
        mbrLoad = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        irInput = new javax.swing.JTextField();
        mbrInput = new javax.swing.JTextField();
        marInput = new javax.swing.JTextField();
        pcInput = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        mfrInput = new javax.swing.JTextField();
        ccInput = new javax.swing.JTextField();
        storeButton = new javax.swing.JButton();
        stPlusButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        initButton = new javax.swing.JButton();
        ssButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();
        haltPanel = new javax.swing.JPanel();
        runPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        inputField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        keyboard = new javax.swing.JTextField();
        printer = new javax.swing.JTextField();
        program1Load = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        console = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(800, 800));
        setSize(new java.awt.Dimension(800, 800));

        gpr0Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpr0InputActionPerformed(evt);
            }
        });

        gpr1Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpr1InputActionPerformed(evt);
            }
        });

        gpr2Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpr2InputActionPerformed(evt);
            }
        });

        gpr3Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpr3InputActionPerformed(evt);
            }
        });

        ixr1Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ixr1InputActionPerformed(evt);
            }
        });

        ixr2Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ixr2InputActionPerformed(evt);
            }
        });

        ixr3Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ixr3InputActionPerformed(evt);
            }
        });

        jLabel1.setText("GPR 3");

        jLabel2.setText("GPR 1");

        jLabel3.setText("GPR 2");

        jLabel4.setText("GPR 0");

        jLabel5.setText("IXR 1");

        jLabel6.setText("IXR 2");

        jLabel7.setText("IXR 3");

        gpr0Load.setText("LOAD");
        gpr0Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpr0LoadActionPerformed(evt);
            }
        });

        gpr1Load.setText("LOAD");
        gpr1Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpr1LoadActionPerformed(evt);
            }
        });

        gpr2Load.setText("LOAD");
        gpr2Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpr2LoadActionPerformed(evt);
            }
        });

        gpr3Load.setText("LOAD");
        gpr3Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpr3LoadActionPerformed(evt);
            }
        });

        ixr1Load.setText("LOAD");
        ixr1Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ixr1LoadActionPerformed(evt);
            }
        });

        ixr2Load.setText("LOAD");
        ixr2Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ixr2LoadActionPerformed(evt);
            }
        });

        ixr3Load.setText("LOAD");
        ixr3Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ixr3LoadActionPerformed(evt);
            }
        });

        jLabel8.setText(" MAR");

        pcLoad.setText("LOAD");
        pcLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcLoadActionPerformed(evt);
            }
        });

        marLoad.setText("LOAD");
        marLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marLoadActionPerformed(evt);
            }
        });

        mbrLoad.setText("LOAD");
        mbrLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbrLoadActionPerformed(evt);
            }
        });

        jLabel9.setText("PC");

        irInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irInputActionPerformed(evt);
            }
        });

        mbrInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbrInputActionPerformed(evt);
            }
        });

        marInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marInputActionPerformed(evt);
            }
        });

        pcInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcInputActionPerformed(evt);
            }
        });

        jLabel10.setText("IR");

        jLabel11.setText("MBR");

        jLabel12.setText("MFR");

        jLabel13.setText("CC");

        mfrInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfrInputActionPerformed(evt);
            }
        });

        ccInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccInputActionPerformed(evt);
            }
        });

        storeButton.setText("STORE");
        storeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeButtonActionPerformed(evt);
            }
        });

        stPlusButton.setText("ST+");
        stPlusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stPlusButtonActionPerformed(evt);
            }
        });

        loadButton.setText("LOAD");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        initButton.setText("INIT");
        initButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initButtonActionPerformed(evt);
            }
        });

        ssButton.setText("SS");
        ssButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssButtonActionPerformed(evt);
            }
        });

        runButton.setText("RUN");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        haltPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout haltPanelLayout = new javax.swing.GroupLayout(haltPanel);
        haltPanel.setLayout(haltPanelLayout);
        haltPanelLayout.setHorizontalGroup(
            haltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        haltPanelLayout.setVerticalGroup(
            haltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        runPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout runPanelLayout = new javax.swing.GroupLayout(runPanel);
        runPanel.setLayout(runPanelLayout);
        runPanelLayout.setHorizontalGroup(
            runPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        runPanelLayout.setVerticalGroup(
            runPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel14.setText("HALT");

        jLabel15.setText("RUN");

        inputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFieldActionPerformed(evt);
            }
        });

        jLabel16.setText("INPUT ");

        keyboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyboardActionPerformed(evt);
            }
        });

        program1Load.setText("LOAD PROGRAM 1");
        program1Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                program1LoadActionPerformed(evt);
            }
        });

        jLabel17.setText("KEYBOARD");

        jLabel18.setText("PRINTER");

        jLabel19.setText("CONSOLE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gpr1Input, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gpr1Load))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gpr2Input, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gpr2Load))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gpr3Input, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gpr3Load))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gpr0Input, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gpr0Load)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pcInput, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(marInput, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pcLoad)
                                    .addComponent(marLoad)))
                            .addComponent(irInput, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mbrInput, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mbrLoad)))
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ixr1Input, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ixr1Load))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ixr2Input, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ixr2Load))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addComponent(jLabel16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(keyboard, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(ixr3Input, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ixr3Load))
                                            .addComponent(inputField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(program1Load, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(49, 49, 49)
                                        .addComponent(storeButton)))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel14))
                                            .addComponent(haltPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(runPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel15))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(stPlusButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(loadButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(initButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ssButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(printer, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(console, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ccInput, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mfrInput, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(147, 147, 147))))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mfrInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ccInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gpr0Input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(gpr0Load))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gpr1Input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(gpr1Load))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gpr2Input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(gpr2Load))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gpr3Input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(gpr3Load))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ixr1Input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(ixr1Load))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ixr2Input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(ixr2Load)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pcInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(pcLoad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(marInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(marLoad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mbrInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(mbrLoad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(irInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ixr3Input, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(ixr3Load)
                    .addComponent(storeButton)
                    .addComponent(stPlusButton)
                    .addComponent(loadButton)
                    .addComponent(initButton)
                    .addComponent(ssButton)
                    .addComponent(runButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(haltPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(runPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputField, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keyboard, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printer, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(program1Load, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(console, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addGap(9, 9, 9))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gpr0InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpr0InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpr0InputActionPerformed

    private void gpr1InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpr1InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpr1InputActionPerformed

    private void gpr2InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpr2InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpr2InputActionPerformed

    private void gpr3InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpr3InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpr3InputActionPerformed

    private void ixr1InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ixr1InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ixr1InputActionPerformed

    private void ixr2InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ixr2InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ixr2InputActionPerformed

    private void ixr3InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ixr3InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ixr3InputActionPerformed

    private void gpr0LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpr0LoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpr0LoadActionPerformed

    private void gpr1LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpr1LoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpr1LoadActionPerformed

    private void gpr2LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpr2LoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpr2LoadActionPerformed

    private void gpr3LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpr3LoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpr3LoadActionPerformed

    private void ixr1LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ixr1LoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ixr1LoadActionPerformed

    private void ixr2LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ixr2LoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ixr2LoadActionPerformed

    private void ixr3LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ixr3LoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ixr3LoadActionPerformed

    private void pcLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcLoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcLoadActionPerformed

    private void marLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marLoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marLoadActionPerformed

    private void mbrLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbrLoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbrLoadActionPerformed

    private void irInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_irInputActionPerformed

    private void mbrInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbrInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbrInputActionPerformed

    private void marInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marInputActionPerformed

    private void pcInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcInputActionPerformed

    private void mfrInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfrInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mfrInputActionPerformed

    private void ccInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccInputActionPerformed

    private void storeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storeButtonActionPerformed

    private void stPlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stPlusButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stPlusButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadButtonActionPerformed

    private void initButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initButtonActionPerformed

    private void ssButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssButtonActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_runButtonActionPerformed

    private void inputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFieldActionPerformed

    private void keyboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyboardActionPerformed

    private void program1LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_program1LoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_program1LoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        // init();
        // store();
        // init();
        // load();
        // init();
        // storePlus();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maven().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ccInput;
    private javax.swing.JTextField console;
    private javax.swing.JTextField gpr0Input;
    private javax.swing.JButton gpr0Load;
    private javax.swing.JTextField gpr1Input;
    private javax.swing.JButton gpr1Load;
    private javax.swing.JTextField gpr2Input;
    private javax.swing.JButton gpr2Load;
    private javax.swing.JTextField gpr3Input;
    private javax.swing.JButton gpr3Load;
    private javax.swing.JPanel haltPanel;
    private javax.swing.JButton initButton;
    public javax.swing.JTextField inputField;
    private javax.swing.JTextField irInput;
    private javax.swing.JTextField ixr1Input;
    private javax.swing.JButton ixr1Load;
    private javax.swing.JTextField ixr2Input;
    private javax.swing.JButton ixr2Load;
    private javax.swing.JTextField ixr3Input;
    private javax.swing.JButton ixr3Load;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField keyboard;
    private javax.swing.JButton loadButton;
    private javax.swing.JTextField marInput;
    private javax.swing.JButton marLoad;
    private javax.swing.JTextField mbrInput;
    private javax.swing.JButton mbrLoad;
    private javax.swing.JTextField mfrInput;
    private javax.swing.JTextField pcInput;
    private javax.swing.JButton pcLoad;
    private javax.swing.JTextField printer;
    private javax.swing.JButton program1Load;
    private javax.swing.JButton runButton;
    private javax.swing.JPanel runPanel;
    private javax.swing.JButton ssButton;
    private javax.swing.JButton stPlusButton;
    private javax.swing.JButton storeButton;
    // End of variables declaration//GEN-END:variables
}
